{"name": "Запрет создания курьеров с одинаковыми данными", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый код: 409, полученный код: 409, ожидаемый текст: Этот логин уже используется,             полученный текст: Этот логин уже используется. Попробуйте другой.\nassert (409 == 409 and 'Этот логин уже используется' == 'Этот логин у...буйте другой.'\n  \n  - Этот логин уже используется. Попробуйте другой.\n  + Этот логин уже используется)", "trace": "self = <test_create_courier.TestCreateCourier object at 0x00000265A48BC110>\nregister_new_courier_and_delete_after_test = {'firstName': 'Amy', 'login': 'daviesmarcus', 'password': '&hzv8Yki_S'}\n\n    @allure.title('Запрет создания курьеров с одинаковыми данными')\n    @allure.description('Создаем двух курьеров с одинаковыми данными, \\\n                        проверяем, что код ответа == 409, текст ответа: \"Этот логин уже используется\"')\n    def test_create_two_couriers_with_the_same_data(self, register_new_courier_and_delete_after_test):\n        requests.post(f'{Data.main_page_url}{Data.api_create_courier}', data=register_new_courier_and_delete_after_test)\n        response = requests.post(f'{Data.main_page_url}{Data.api_create_courier}', data=register_new_courier_and_delete_after_test)\n        r = response.json()\n>       assert 409 == r['code'] and Data.text_create_409 == r['message'], \\\n            f'Ожидаемый код: 409, полученный код: {r['code']}, ожидаемый текст: {Data.text_create_409}, \\\n            полученный текст: {r['message']}'\nE       AssertionError: Ожидаемый код: 409, полученный код: 409, ожидаемый текст: Этот логин уже используется,             полученный текст: Этот логин уже используется. Попробуйте другой.\nE       assert (409 == 409 and 'Этот логин уже используется' == 'Этот логин у...буйте другой.'\nE         \nE         - Этот логин уже используется. Попробуйте другой.\nE         + Этот логин уже используется)\n\ntests\\test_create_courier.py:23: AssertionError"}, "description": "Создаем двух курьеров с одинаковыми данными,                         проверяем, что код ответа == 409, текст ответа: \"Этот логин уже используется\"", "start": 1719995274712, "stop": 1719995274895, "uuid": "c55a47ff-3d87-4e47-8402-96eb0cc0b18d", "historyId": "1a88e76eb6b6d2659e9e2dfa83a38efb", "testCaseId": "1a88e76eb6b6d2659e9e2dfa83a38efb", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_two_couriers_with_the_same_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "InnaNB"}, {"name": "thread", "value": "5680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}